# Generated by Django 4.2.23 on 2025-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_author_book_bookclub_booklist_bookrecommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bookclub_images/'),
        ),
    ]
