# Generated by Django 4.2.23 on 2025-07-31 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, help_text='URL for external profile image', max_length=500, null=True)),
                ('image_updated_at', models.DateTimeField(blank=True, help_text='When the profile image was last updated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='external_id',
            field=models.CharField(blank=True, help_text='External API ID (Open Library, Google Books, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the book cover image was last updated', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.CharField(blank=True, help_text='URL for external book cover image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('openlibrary', 'Open Library'), ('googlebooks', 'Google Books'), ('goodreads', 'Goodreads'), ('manual', 'Manual Entry')], default='manual', help_text='Source of the book data', max_length=20),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='external_id',
            field=models.CharField(blank=True, help_text='External platform ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='image_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the book club image was last updated', null=True),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='image_url',
            field=models.CharField(blank=True, help_text='URL for external book club image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='source',
            field=models.CharField(choices=[('goodreads', 'Goodreads'), ('facebook', 'Facebook Groups'), ('meetup', 'Meetup'), ('manual', 'Manual Entry')], default='manual', help_text='Source of the book club data', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('external_id', 'source'), name='unique_external_id_source'),
        ),
        migrations.AddConstraint(
            model_name='bookclub',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('external_id', 'source'), name='unique_bookclub_external_id_source'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
